<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="LiteDB" Version="5.0.21" />
		<PackageReference Include="LiteDB.Async" Version="0.1.8" />
		<PackageReference Include="MemoryPack" Version="1.21.1" />
		<PackageReference Include="MemoryPack.AspNetCoreMvcFormatter" Version="1.21.1" />
		<PackageReference Include="protobuf-net" Version="3.2.30" />
		<PackageReference Include="protobuf-net.BuildTools" Version="3.2.33">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="RestSharp" Version="111.2.0" />
	</ItemGroup>

	<ItemGroup>
		<CompilerVisibleProperty Include="MemoryPackGenerator_TypeScriptOutputDirectory" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="wwwroot\js\" />
	</ItemGroup>
	<PropertyGroup>
		<MemoryPackGenerator_TypeScriptOutputDirectory>$(MSBuildProjectDirectory)\wwwroot\js\memorypack</MemoryPackGenerator_TypeScriptOutputDirectory>
	</PropertyGroup>

</Project>